# Generated by Django 4.0.6 on 2022-07-26 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batch_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('room_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True)),
                ('projector', models.IntegerField(blank=True)),
                ('ac', models.IntegerField(blank=True)),
                ('computer', models.IntegerField(blank=True)),
                ('desks', models.IntegerField(blank=True)),
                ('whiteboard', models.IntegerField(blank=True)),
                ('count', models.IntegerField(blank=True)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('track_core', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('ta', models.CharField(max_length=100)),
                ('lecture_hrs', models.IntegerField(blank=True)),
                ('tut_hrs', models.IntegerField(blank=True)),
                ('capacity', models.IntegerField(blank=True)),
                ('lab_hrs', models.IntegerField(blank=True)),
                ('lab_capacity', models.IntegerField(blank=True)),
                ('assigned_room', models.IntegerField(blank=True)),
                ('assigned_lab', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('dept_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_id', models.CharField(default='', max_length=50)),
                ('time', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('monday', models.CharField(max_length=100)),
                ('tuesday', models.CharField(max_length=100)),
                ('wednesday', models.CharField(max_length=100)),
                ('thursday', models.CharField(max_length=100)),
                ('friday', models.CharField(max_length=100)),
                ('saturday', models.CharField(blank=True, max_length=100)),
                ('batch_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.batch')),
                ('dept_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.dept')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('prn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=255)),
                ('dept_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.dept')),
            ],
        ),
        migrations.CreateModel(
            name='faculties',
            fields=[
                ('fac_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fac_name', models.CharField(max_length=100)),
                ('fac_role', models.CharField(max_length=100)),
                ('dept_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.dept')),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('exam_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('exam_type', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.course')),
                ('dept_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.dept')),
                ('prn', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.students')),
                ('room_no', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='model_name.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept_id',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.dept'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.students'),
        ),
        migrations.AddField(
            model_name='batch',
            name='dept_id',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.dept'),
        ),
    ]
