# Generated by Django 4.0.6 on 2022-07-26 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_name', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='time',
            new_name='t_time',
        ),
    ]
