# Generated by Django 4.0.6 on 2022-07-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_name', '0002_rename_time_timetable_t_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='t_time',
            new_name='time',
        ),
    ]
