# Generated by Django 4.0.6 on 2022-07-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_name', '0003_rename_t_time_timetable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.CharField(default='notStarted', max_length=255),
        ),
    ]
