# Generated by Django 4.0.6 on 2022-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_name', '0004_alter_classroom_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='sem',
            fields=[
                ('semester', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
