# Generated by Django 4.0.6 on 2022-07-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_name', '0006_faculties_fac_cab_no_alter_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.students'),
        ),
        migrations.AlterField(
            model_name='students',
            name='dept_id',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.dept'),
        ),
    ]
