# Generated by Django 4.0.6 on 2022-07-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_name', '0007_alter_course_semester_alter_students_dept_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255)),
                ('status_req', models.CharField(max_length=255)),
                ('dept_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.dept')),
                ('fac_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.faculties')),
                ('prn', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='model_name.students')),
            ],
        ),
    ]
