# Generated by Django 4.0.6 on 2022-07-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_name', '0008_meeting_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_req',
            name='id',
        ),
        migrations.AlterField(
            model_name='meeting_req',
            name='request_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
