# Generated by Django 4.0.6 on 2022-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_name', '0012_alter_batch_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='available',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
