# Generated by Django 4.0.6 on 2022-08-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_name', '0014_alter_faculties_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculties',
            old_name='available',
            new_name='availability',
        ),
    ]
